manifest:
  self:
    path: hid-rp
  defaults:
    remote: IntergatedCircuits

  remotes:
    - name: IntergatedCircuits
      url-base: https://github.com/IntergatedCircuits

  projects:
    - name: bitfilled
      revision: 58bda56b80bb7dc78b9e4413c3ebabb3a8a6e6ae
