manifest:
  self:
    path: hid-rp
  defaults:
    remote: IntergatedCircuits

  remotes:
    - name: IntergatedCircuits
      url-base: https://github.com/IntergatedCircuits

  projects:
    - name: bitfilled
      revision: 60673d361f36b7f2e53c26a10fcbc3d1e71510a6
