#ifndef __HID_PAGE_GENERIC_DESKTOP_H_
#define __HID_PAGE_GENERIC_DESKTOP_H_

#include "hid/usage.h"

namespace hid::page
{
    enum class generic_desktop : usage_id_type;
    template<>
    struct info<generic_desktop>
    {
        constexpr static usage_id_type base_id = 0x00010000;
        constexpr static usage_id_type max_usage = 0x00e2 | base_id;
        constexpr static const char* name = "Generic Desktop Controls";
    };
    enum class generic_desktop : usage_id_type
    {
        POINTER = 0x0001 | info<generic_desktop>::base_id,
        MOUSE = 0x0002 | info<generic_desktop>::base_id,
        JOYSTICK = 0x0004 | info<generic_desktop>::base_id,
        GAME_PAD = 0x0005 | info<generic_desktop>::base_id,
        KEYBOARD = 0x0006 | info<generic_desktop>::base_id,
        KEYPAD = 0x0007 | info<generic_desktop>::base_id,
        MULTI_AXIS_CONTROLLER = 0x0008 | info<generic_desktop>::base_id,
        TABLET_PC_SYSTEM_CONTROLS = 0x0009 | info<generic_desktop>::base_id,
        WATER_COOLING_DEVICE = 0x000a | info<generic_desktop>::base_id,
        COMPUTER_CHASSIS_DEVICE = 0x000b | info<generic_desktop>::base_id,
        WIRELESS_RADIO_CONTROLS = 0x000c | info<generic_desktop>::base_id,
        PORTABLE_DEVICE_CONTROL = 0x000d | info<generic_desktop>::base_id,
        SYSTEM_MULTI_AXIS_CONTROLLER = 0x000e | info<generic_desktop>::base_id,
        SPATIAL_CONTROLLER = 0x000f | info<generic_desktop>::base_id,
        ASSISTIVE_CONTROL = 0x0010 | info<generic_desktop>::base_id,
        DEVICE_DOCK = 0x0011 | info<generic_desktop>::base_id,
        DOCKABLE_DEVICE = 0x0012 | info<generic_desktop>::base_id,
        CALL_STATE_MANAGEMENT_CONTROL = 0x0013 | info<generic_desktop>::base_id,
        X = 0x0030 | info<generic_desktop>::base_id,
        Y = 0x0031 | info<generic_desktop>::base_id,
        Z = 0x0032 | info<generic_desktop>::base_id,
        RX = 0x0033 | info<generic_desktop>::base_id,
        RY = 0x0034 | info<generic_desktop>::base_id,
        RZ = 0x0035 | info<generic_desktop>::base_id,
        SLIDER = 0x0036 | info<generic_desktop>::base_id,
        DIAL = 0x0037 | info<generic_desktop>::base_id,
        WHEEL = 0x0038 | info<generic_desktop>::base_id,
        HAT_SWITCH = 0x0039 | info<generic_desktop>::base_id,
        COUNTER_BUFFER = 0x003a | info<generic_desktop>::base_id,
        BYTE_COUNT = 0x003b | info<generic_desktop>::base_id,
        MOTION_WAKEUP = 0x003c | info<generic_desktop>::base_id,
        START = 0x003d | info<generic_desktop>::base_id,
        SELECT = 0x003e | info<generic_desktop>::base_id,
        VX = 0x0040 | info<generic_desktop>::base_id,
        VY = 0x0041 | info<generic_desktop>::base_id,
        VZ = 0x0042 | info<generic_desktop>::base_id,
        VBRX = 0x0043 | info<generic_desktop>::base_id,
        VBRY = 0x0044 | info<generic_desktop>::base_id,
        VBRZ = 0x0045 | info<generic_desktop>::base_id,
        VNO = 0x0046 | info<generic_desktop>::base_id,
        FEATURE_NOTIFICATION = 0x0047 | info<generic_desktop>::base_id,
        RESOLUTION_MULTIPLIER = 0x0048 | info<generic_desktop>::base_id,
        QX = 0x0049 | info<generic_desktop>::base_id,
        QY = 0x004a | info<generic_desktop>::base_id,
        QZ = 0x004b | info<generic_desktop>::base_id,
        QW = 0x004c | info<generic_desktop>::base_id,
        SYSTEM_CONTROL = 0x0080 | info<generic_desktop>::base_id,
        SYSTEM_POWER_DOWN = 0x0081 | info<generic_desktop>::base_id,
        SYSTEM_SLEEP = 0x0082 | info<generic_desktop>::base_id,
        SYSTEM_WAKE_UP = 0x0083 | info<generic_desktop>::base_id,
        SYSTEM_CONTEXT_MENU = 0x0084 | info<generic_desktop>::base_id,
        SYSTEM_MAIN_MENU = 0x0085 | info<generic_desktop>::base_id,
        SYSTEM_APP_MENU = 0x0086 | info<generic_desktop>::base_id,
        SYSTEM_MENU_HELP = 0x0087 | info<generic_desktop>::base_id,
        SYSTEM_MENU_EXIT = 0x0088 | info<generic_desktop>::base_id,
        SYSTEM_MENU_SELECT = 0x0089 | info<generic_desktop>::base_id,
        SYSTEM_MENU_RIGHT = 0x008a | info<generic_desktop>::base_id,
        SYSTEM_MENU_LEFT = 0x008b | info<generic_desktop>::base_id,
        SYSTEM_MENU_UP = 0x008c | info<generic_desktop>::base_id,
        SYSTEM_MENU_DOWN = 0x008d | info<generic_desktop>::base_id,
        SYSTEM_COLD_RESTART = 0x008e | info<generic_desktop>::base_id,
        SYSTEM_WARM_RESTART = 0x008f | info<generic_desktop>::base_id,
        D_PAD_UP = 0x0090 | info<generic_desktop>::base_id,
        D_PAD_DOWN = 0x0091 | info<generic_desktop>::base_id,
        D_PAD_RIGHT = 0x0092 | info<generic_desktop>::base_id,
        D_PAD_LEFT = 0x0093 | info<generic_desktop>::base_id,
        INDEX_TRIGGER = 0x0094 | info<generic_desktop>::base_id,
        PALM_TRIGGER = 0x0095 | info<generic_desktop>::base_id,
        THUMBSTICK = 0x0096 | info<generic_desktop>::base_id,
        SYSTEM_FUNCTION_SHIFT = 0x0097 | info<generic_desktop>::base_id,
        SYSTEM_FUNCTION_SHIFT_LOCK = 0x0098 | info<generic_desktop>::base_id,
        SYSTEM_FUNCTION_SHIFT_LOCK_INDICATOR = 0x0099 | info<generic_desktop>::base_id,
        SYSTEM_DISMISS_NOTIFICATION = 0x009a | info<generic_desktop>::base_id,
        SYSTEM_DO_NOT_DISTURB = 0x009b | info<generic_desktop>::base_id,
        SYSTEM_DOCK = 0x00a0 | info<generic_desktop>::base_id,
        SYSTEM_UNDOCK = 0x00a1 | info<generic_desktop>::base_id,
        SYSTEM_SETUP = 0x00a2 | info<generic_desktop>::base_id,
        SYSTEM_BREAK = 0x00a3 | info<generic_desktop>::base_id,
        SYSTEM_DEBUGGER_BREAK = 0x00a4 | info<generic_desktop>::base_id,
        APPLICATION_BREAK = 0x00a5 | info<generic_desktop>::base_id,
        APPLICATION_DEBUGGER_BREAK = 0x00a6 | info<generic_desktop>::base_id,
        SYSTEM_SPEAKER_MUTE = 0x00a7 | info<generic_desktop>::base_id,
        SYSTEM_HIBERNATE = 0x00a8 | info<generic_desktop>::base_id,
        SYSTEM_DISPLAY_INVERT = 0x00b0 | info<generic_desktop>::base_id,
        SYSTEM_DISPLAY_INTERNAL = 0x00b1 | info<generic_desktop>::base_id,
        SYSTEM_DISPLAY_EXTERNAL = 0x00b2 | info<generic_desktop>::base_id,
        SYSTEM_DISPLAY_BOTH = 0x00b3 | info<generic_desktop>::base_id,
        SYSTEM_DISPLAY_DUAL = 0x00b4 | info<generic_desktop>::base_id,
        SYSTEM_DISPLAY_TOGGLE_INT_EXT = 0x00b5 | info<generic_desktop>::base_id,
        SYSTEM_DISPLAY_SWAP_PRIMARY_SECONDARY = 0x00b6 | info<generic_desktop>::base_id,
        SYSTEM_DISPLAY_LCD_AUTOSCALE = 0x00b7 | info<generic_desktop>::base_id,
        SENSOR_ZONE = 0x00c0 | info<generic_desktop>::base_id,
        RPM = 0x00c1 | info<generic_desktop>::base_id,
        COOLANT_LEVEL = 0x00c2 | info<generic_desktop>::base_id,
        COOLANT_CRITICAL_LEVEL = 0x00c3 | info<generic_desktop>::base_id,
        COOLANT_PUMP = 0x00c4 | info<generic_desktop>::base_id,
        CHASSIS_ENCLOSURE = 0x00c5 | info<generic_desktop>::base_id,
        WIRELESS_RADIO_BUTTON = 0x00c6 | info<generic_desktop>::base_id,
        WIRELESS_RADIO_LED = 0x00c7 | info<generic_desktop>::base_id,
        WIRELESS_RADIO_SLIDER_SWITCH = 0x00c8 | info<generic_desktop>::base_id,
        SYSTEM_DISPLAY_ROTATION_LOCK_BUTTON = 0x00c9 | info<generic_desktop>::base_id,
        SYSTEM_DISPLAY_ROTATION_LOCK_SLIDER_SWITCH = 0x00ca | info<generic_desktop>::base_id,
        CONTROL_ENABLE = 0x00cb | info<generic_desktop>::base_id,
        DOCKABLE_DEVICE_UNIQUE_ID = 0x00d0 | info<generic_desktop>::base_id,
        DOCKABLE_DEVICE_VENDOR_ID = 0x00d1 | info<generic_desktop>::base_id,
        DOCKABLE_DEVICE_PRIMARY_USAGE_PAGE = 0x00d2 | info<generic_desktop>::base_id,
        DOCKABLE_DEVICE_PRIMARY_USAGE_ID = 0x00d3 | info<generic_desktop>::base_id,
        DOCKABLE_DEVICE_DOCKING_STATE = 0x00d4 | info<generic_desktop>::base_id,
        DOCKABLE_DEVICE_DISPLAY_OCCLUSION = 0x00d5 | info<generic_desktop>::base_id,
        DOCKABLE_DEVICE_OBJECT_TYPE = 0x00d6 | info<generic_desktop>::base_id,
        CALL_ACTIVE_LED = 0x00e0 | info<generic_desktop>::base_id,
        CALL_MUTE_TOGGLE = 0x00e1 | info<generic_desktop>::base_id,
        CALL_MUTE_LED = 0x00e2 | info<generic_desktop>::base_id,
    };
}

#endif // __HID_PAGE_GENERIC_DESKTOP_H_

