#ifndef __HID_PAGE_PHYSICAL_INTERFACE_DEVICE_H_
#define __HID_PAGE_PHYSICAL_INTERFACE_DEVICE_H_

#include "hid/usage.h"

namespace hid::page
{
    enum class physical_interface_device : usage_id_type;
    template<>
    struct info<physical_interface_device>
    {
        constexpr static usage_id_type base_id = 0x000f0000;
        constexpr static usage_id_type max_usage = 0x00ac | base_id;
        constexpr static const char* name = "Physical Interface Device";
    };
    enum class physical_interface_device : usage_id_type
    {
        PHYSICAL_INTERFACE_DEVICE = 0x0001 | info<physical_interface_device>::base_id,
        NORMAL = 0x0020 | info<physical_interface_device>::base_id,
        SET_EFFECT_REPORT = 0x0021 | info<physical_interface_device>::base_id,
        EFFECT_BLOCK_INDEX = 0x0022 | info<physical_interface_device>::base_id,
        PARAMETER_BLOCK_OFFSET = 0x0023 | info<physical_interface_device>::base_id,
        ROM_FLAG = 0x0024 | info<physical_interface_device>::base_id,
        EFFECT_TYPE = 0x0025 | info<physical_interface_device>::base_id,
        ET_CONSTANT_FORCE = 0x0026 | info<physical_interface_device>::base_id,
        ET_RAMP = 0x0027 | info<physical_interface_device>::base_id,
        ET_CUSTOM_FORCE_DATA = 0x0028 | info<physical_interface_device>::base_id,
        ET_SQUARE = 0x0030 | info<physical_interface_device>::base_id,
        ET_SINE = 0x0031 | info<physical_interface_device>::base_id,
        ET_TRIANGLE = 0x0032 | info<physical_interface_device>::base_id,
        ET_SAWTOOTH_UP = 0x0033 | info<physical_interface_device>::base_id,
        ET_SAWTOOTH_DOWN = 0x0034 | info<physical_interface_device>::base_id,
        ET_SPRING = 0x0040 | info<physical_interface_device>::base_id,
        ET_DAMPER = 0x0041 | info<physical_interface_device>::base_id,
        ET_INERTIA = 0x0042 | info<physical_interface_device>::base_id,
        ET_FRICTION = 0x0043 | info<physical_interface_device>::base_id,
        DURATION = 0x0050 | info<physical_interface_device>::base_id,
        SAMPLE_PERIOD = 0x0051 | info<physical_interface_device>::base_id,
        GAIN = 0x0052 | info<physical_interface_device>::base_id,
        TRIGGER_BUTTON = 0x0053 | info<physical_interface_device>::base_id,
        TRIGGER_REPEAT_INTERVAL = 0x0054 | info<physical_interface_device>::base_id,
        AXES_ENABLE = 0x0055 | info<physical_interface_device>::base_id,
        DIRECTION_ENABLE = 0x0056 | info<physical_interface_device>::base_id,
        DIRECTION = 0x0057 | info<physical_interface_device>::base_id,
        TYPE_SPECIFIC_BLOCK_OFFSET = 0x0058 | info<physical_interface_device>::base_id,
        BLOCK_TYPE = 0x0059 | info<physical_interface_device>::base_id,
        SET_ENVELOPE_REPORT = 0x005a | info<physical_interface_device>::base_id,
        ATTACK_LEVEL = 0x005b | info<physical_interface_device>::base_id,
        ATTACK_TIME = 0x005c | info<physical_interface_device>::base_id,
        FADE_LEVEL = 0x005d | info<physical_interface_device>::base_id,
        FADE_TIME = 0x005e | info<physical_interface_device>::base_id,
        SET_CONDITION_REPORT = 0x005f | info<physical_interface_device>::base_id,
        CP_OFFSET = 0x0060 | info<physical_interface_device>::base_id,
        POSITIVE_COEFFICIENT = 0x0061 | info<physical_interface_device>::base_id,
        NEGATIVE_COEFFICIENT = 0x0062 | info<physical_interface_device>::base_id,
        POSITIVE_SATURATION = 0x0063 | info<physical_interface_device>::base_id,
        NEGATIVE_SATURATION = 0x0064 | info<physical_interface_device>::base_id,
        DEAD_BAND = 0x0065 | info<physical_interface_device>::base_id,
        DOWNLOAD_FORCE_SAMPLE = 0x0066 | info<physical_interface_device>::base_id,
        ISOCH_CUSTOM_FORCE_ENABLE = 0x0067 | info<physical_interface_device>::base_id,
        CUSTOM_FORCE_DATA_REPORT = 0x0068 | info<physical_interface_device>::base_id,
        CUSTOM_FORCE_DATA = 0x0069 | info<physical_interface_device>::base_id,
        CUSTOM_FORCE_VENDOR_DEFINED_DATA = 0x006a | info<physical_interface_device>::base_id,
        SET_CUSTOM_FORCE_REPORT = 0x006b | info<physical_interface_device>::base_id,
        CUSTOM_FORCE_DATA_OFFSET = 0x006c | info<physical_interface_device>::base_id,
        SAMPLE_COUNT = 0x006d | info<physical_interface_device>::base_id,
        SET_PERIODIC_REPORT = 0x006e | info<physical_interface_device>::base_id,
        OFFSET = 0x006f | info<physical_interface_device>::base_id,
        MAGNITUDE = 0x0070 | info<physical_interface_device>::base_id,
        PHASE = 0x0071 | info<physical_interface_device>::base_id,
        PERIOD = 0x0072 | info<physical_interface_device>::base_id,
        SET_CONSTANT_FORCE_REPORT = 0x0073 | info<physical_interface_device>::base_id,
        SET_RAMP_FORCE_REPORT = 0x0074 | info<physical_interface_device>::base_id,
        RAMP_START = 0x0075 | info<physical_interface_device>::base_id,
        RAMP_END = 0x0076 | info<physical_interface_device>::base_id,
        EFFECT_OPERATION_REPORT = 0x0077 | info<physical_interface_device>::base_id,
        EFFECT_OPERATION = 0x0078 | info<physical_interface_device>::base_id,
        OP_EFFECT_START = 0x0079 | info<physical_interface_device>::base_id,
        OP_EFFECT_START_SOLO = 0x007a | info<physical_interface_device>::base_id,
        OP_EFFECT_STOP = 0x007b | info<physical_interface_device>::base_id,
        LOOP_COUNT = 0x007c | info<physical_interface_device>::base_id,
        DEVICE_GAIN_REPORT = 0x007d | info<physical_interface_device>::base_id,
        DEVICE_GAIN = 0x007e | info<physical_interface_device>::base_id,
        PID_POOL_REPORT = 0x007f | info<physical_interface_device>::base_id,
        RAM_POOL_SIZE = 0x0080 | info<physical_interface_device>::base_id,
        ROM_POOL_SIZE = 0x0081 | info<physical_interface_device>::base_id,
        ROM_EFFECT_BLOCK_COUNT = 0x0082 | info<physical_interface_device>::base_id,
        SIMULTANEOUS_EFFECTS_MAX = 0x0083 | info<physical_interface_device>::base_id,
        POOL_ALIGNMENT = 0x0084 | info<physical_interface_device>::base_id,
        PID_POOL_MOVE_REPORT = 0x0085 | info<physical_interface_device>::base_id,
        MOVE_SOURCE = 0x0086 | info<physical_interface_device>::base_id,
        MOVE_DESTINATION = 0x0087 | info<physical_interface_device>::base_id,
        MOVE_LENGTH = 0x0088 | info<physical_interface_device>::base_id,
        PID_BLOCK_LOAD_REPORT = 0x0089 | info<physical_interface_device>::base_id,
        BLOCK_LOAD_STATUS = 0x008b | info<physical_interface_device>::base_id,
        BLOCK_LOAD_SUCCESS = 0x008c | info<physical_interface_device>::base_id,
        BLOCK_LOAD_FULL = 0x008d | info<physical_interface_device>::base_id,
        BLOCK_LOAD_ERROR = 0x008e | info<physical_interface_device>::base_id,
        BLOCK_HANDLE = 0x008f | info<physical_interface_device>::base_id,
        PID_BLOCK_FREE_REPORT = 0x0090 | info<physical_interface_device>::base_id,
        TYPE_SPECIFIC_BLOCK_HANDLE = 0x0091 | info<physical_interface_device>::base_id,
        PID_STATE_REPORT = 0x0092 | info<physical_interface_device>::base_id,
        EFFECT_PLAYING = 0x0094 | info<physical_interface_device>::base_id,
        PID_DEVICE_CONTROL_REPORT = 0x0095 | info<physical_interface_device>::base_id,
        PID_DEVICE_CONTROL = 0x0096 | info<physical_interface_device>::base_id,
        DC_ENABLE_ACTUATORS = 0x0097 | info<physical_interface_device>::base_id,
        DC_DISABLE_ACTUATORS = 0x0098 | info<physical_interface_device>::base_id,
        DC_STOP_ALL_EFFECTS = 0x0099 | info<physical_interface_device>::base_id,
        DC_DEVICE_RESET = 0x009a | info<physical_interface_device>::base_id,
        DC_DEVICE_PAUSE = 0x009b | info<physical_interface_device>::base_id,
        DC_DEVICE_CONTINUE = 0x009c | info<physical_interface_device>::base_id,
        DEVICE_PAUSED = 0x009f | info<physical_interface_device>::base_id,
        ACTUATORS_ENABLED = 0x00a0 | info<physical_interface_device>::base_id,
        SAFETY_SWITCH = 0x00a4 | info<physical_interface_device>::base_id,
        ACTUATOR_OVERRIDE_SWITCH = 0x00a5 | info<physical_interface_device>::base_id,
        ACTUATOR_POWER = 0x00a6 | info<physical_interface_device>::base_id,
        START_DELAY = 0x00a7 | info<physical_interface_device>::base_id,
        PARAMETER_BLOCK_SIZE = 0x00a8 | info<physical_interface_device>::base_id,
        DEVICE_MANAGED_POOL = 0x00a9 | info<physical_interface_device>::base_id,
        SHARED_PARAMETER_BLOCKS = 0x00aa | info<physical_interface_device>::base_id,
        CREATE_NEW_EFFECT_REPORT = 0x00ab | info<physical_interface_device>::base_id,
        RAM_POOL_AVAILABLE = 0x00ac | info<physical_interface_device>::base_id,
    };
}

#endif // __HID_PAGE_PHYSICAL_INTERFACE_DEVICE_H_

