#ifndef __HID_PAGE_TELEPHONY_H_
#define __HID_PAGE_TELEPHONY_H_

#include "hid/usage.h"

namespace hid::page
{
    enum class telephony : usage_id_type;
    template<>
    struct info<telephony>
    {
        constexpr static usage_id_type base_id = 0x000b0000;
        constexpr static usage_id_type max_usage = 0x014b | base_id;
        constexpr static const char* name = "Telephony";
    };
    enum class telephony : usage_id_type
    {
        PHONE = 0x0001 | info<telephony>::base_id,
        ANSWERING_MACHINE = 0x0002 | info<telephony>::base_id,
        MESSAGE_CONTROLS = 0x0003 | info<telephony>::base_id,
        HANDSET = 0x0004 | info<telephony>::base_id,
        HEADSET = 0x0005 | info<telephony>::base_id,
        TELEPHONY_KEY_PAD = 0x0006 | info<telephony>::base_id,
        PROGRAMMABLE_BUTTON = 0x0007 | info<telephony>::base_id,
        HOOK_SWITCH = 0x0020 | info<telephony>::base_id,
        FLASH = 0x0021 | info<telephony>::base_id,
        FEATURE = 0x0022 | info<telephony>::base_id,
        HOLD = 0x0023 | info<telephony>::base_id,
        REDIAL = 0x0024 | info<telephony>::base_id,
        TRANSFER = 0x0025 | info<telephony>::base_id,
        DROP = 0x0026 | info<telephony>::base_id,
        PARK = 0x0027 | info<telephony>::base_id,
        FORWARD_CALLS = 0x0028 | info<telephony>::base_id,
        ALTERNATE_FUNCTION = 0x0029 | info<telephony>::base_id,
        LINE = 0x002a | info<telephony>::base_id,
        SPEAKER_PHONE = 0x002b | info<telephony>::base_id,
        CONFERENCE = 0x002c | info<telephony>::base_id,
        RING_ENABLE = 0x002d | info<telephony>::base_id,
        RING_SELECT = 0x002e | info<telephony>::base_id,
        PHONE_MUTE = 0x002f | info<telephony>::base_id,
        CALLER_ID = 0x0030 | info<telephony>::base_id,
        SPEED_DIAL = 0x0050 | info<telephony>::base_id,
        STORE_NUMBER = 0x0051 | info<telephony>::base_id,
        RECALL_NUMBER = 0x0052 | info<telephony>::base_id,
        PHONE_DIRECTORY = 0x0053 | info<telephony>::base_id,
        VOICE_MAIL = 0x0070 | info<telephony>::base_id,
        SCREEN_CALLS = 0x0071 | info<telephony>::base_id,
        DO_NOT_DISTURB = 0x0072 | info<telephony>::base_id,
        MESSAGE = 0x0073 | info<telephony>::base_id,
        ANSWER_ON_OFF = 0x0074 | info<telephony>::base_id,
        INSIDE_DIAL_TONE = 0x0090 | info<telephony>::base_id,
        OUTSIDE_DIAL_TONE = 0x0091 | info<telephony>::base_id,
        INSIDE_RING_TONE = 0x0092 | info<telephony>::base_id,
        OUTSIDE_RING_TONE = 0x0093 | info<telephony>::base_id,
        PRIORITY_RING_TONE = 0x0094 | info<telephony>::base_id,
        INSIDE_RINGBACK = 0x0095 | info<telephony>::base_id,
        PRIORITY_RINGBACK = 0x0096 | info<telephony>::base_id,
        LINE_BUSY_TONE = 0x0097 | info<telephony>::base_id,
        REORDER_TONE = 0x0098 | info<telephony>::base_id,
        CALL_WAITING_TONE = 0x0099 | info<telephony>::base_id,
        CONFIRMATION_TONE_1 = 0x009a | info<telephony>::base_id,
        CONFIRMATION_TONE_2 = 0x009b | info<telephony>::base_id,
        TONES_OFF = 0x009c | info<telephony>::base_id,
        OUTSIDE_RINGBACK = 0x009d | info<telephony>::base_id,
        RINGER = 0x009e | info<telephony>::base_id,
        PHONE_KEY_0 = 0x00b0 | info<telephony>::base_id,
        PHONE_KEY_1 = 0x00b1 | info<telephony>::base_id,
        PHONE_KEY_2 = 0x00b2 | info<telephony>::base_id,
        PHONE_KEY_3 = 0x00b3 | info<telephony>::base_id,
        PHONE_KEY_4 = 0x00b4 | info<telephony>::base_id,
        PHONE_KEY_5 = 0x00b5 | info<telephony>::base_id,
        PHONE_KEY_6 = 0x00b6 | info<telephony>::base_id,
        PHONE_KEY_7 = 0x00b7 | info<telephony>::base_id,
        PHONE_KEY_8 = 0x00b8 | info<telephony>::base_id,
        PHONE_KEY_9 = 0x00b9 | info<telephony>::base_id,
        PHONE_KEY_STAR = 0x00ba | info<telephony>::base_id,
        PHONE_KEY_POUND = 0x00bb | info<telephony>::base_id,
        PHONE_KEY_A = 0x00bc | info<telephony>::base_id,
        PHONE_KEY_B = 0x00bd | info<telephony>::base_id,
        PHONE_KEY_C = 0x00be | info<telephony>::base_id,
        PHONE_KEY_D = 0x00bf | info<telephony>::base_id,
        PHONE_KEY_CALL_HISTORY = 0x00c0 | info<telephony>::base_id,
        PHONE_KEY_CALLER_ID = 0x00c1 | info<telephony>::base_id,
        PHONE_KEY_SETTINGS = 0x00c2 | info<telephony>::base_id,
        HOST_CONTROL = 0x00f0 | info<telephony>::base_id,
        HOST_AVAILABLE = 0x00f1 | info<telephony>::base_id,
        HOST_CALL_ACTIVE = 0x00f2 | info<telephony>::base_id,
        ACTIVATE_HANDSET_AUDIO = 0x00f3 | info<telephony>::base_id,
        RING_TYPE = 0x00f4 | info<telephony>::base_id,
        RE_DIALABLE_PHONE_NUMBER = 0x00f5 | info<telephony>::base_id,
        STOP_RING_TONE = 0x00f8 | info<telephony>::base_id,
        PSTN_RING_TONE = 0x00f9 | info<telephony>::base_id,
        HOST_RING_TONE = 0x00fa | info<telephony>::base_id,
        ALERT_SOUND_ERROR = 0x00fb | info<telephony>::base_id,
        ALERT_SOUND_CONFIRM = 0x00fc | info<telephony>::base_id,
        ALERT_SOUND_NOTIFICATION = 0x00fd | info<telephony>::base_id,
        SILENT_RING = 0x00fe | info<telephony>::base_id,
        EMAIL_MESSAGE_WAITING = 0x0108 | info<telephony>::base_id,
        VOICEMAIL_MESSAGE_WAITING = 0x0109 | info<telephony>::base_id,
        HOST_HOLD = 0x010a | info<telephony>::base_id,
        INCOMING_CALL_HISTORY_COUNT = 0x0110 | info<telephony>::base_id,
        OUTGOING_CALL_HISTORY_COUNT = 0x0111 | info<telephony>::base_id,
        INCOMING_CALL_HISTORY = 0x0112 | info<telephony>::base_id,
        OUTGOING_CALL_HISTORY = 0x0113 | info<telephony>::base_id,
        PHONE_LOCALE = 0x0114 | info<telephony>::base_id,
        PHONE_TIME_SECOND = 0x0140 | info<telephony>::base_id,
        PHONE_TIME_MINUTE = 0x0141 | info<telephony>::base_id,
        PHONE_TIME_HOUR = 0x0142 | info<telephony>::base_id,
        PHONE_TIME_DAY = 0x0143 | info<telephony>::base_id,
        PHONE_TIME_MONTH = 0x0144 | info<telephony>::base_id,
        PHONE_TIME_YEAR = 0x0145 | info<telephony>::base_id,
        HANDSET_NICKNAME = 0x0146 | info<telephony>::base_id,
        ADDRESS_BOOK_ID = 0x0147 | info<telephony>::base_id,
        CALL_DURATION = 0x014a | info<telephony>::base_id,
        DUAL_MODE_PHONE = 0x014b | info<telephony>::base_id,
    };
}

#endif // __HID_PAGE_TELEPHONY_H_

